#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

# https://wiki.gentoo.org/wiki/EMERGE_DEFAULT_OPTS
target="/etc/portage/emerge_default_opts.conf"

cores=$(grep -c processor /proc/cpuinfo)
more_cores=$(($cores + 1))

echo -e "# THIS FILE IS AUTOMATICALLY GENERATED BY ${0}\n" > "${target}"
echo -e "EMERGE_DEFAULT_OPTS=\"--jobs=${more_cores} --tree --nospinner --quiet-build=y --verbose-conflicts\"" >> "${target}"

source_line="source ${target}"
grep -E "^${source_line}$" /etc/portage/make.conf > /dev/null || { echo "${0}: ERROR, the line: \`${source_line}\` was not found in /etc/portage/make.conf" ; exit 1 ; }
